/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ayf.reports.views;

import com.sun.tools.corba.se.idl.InvalidArgument;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import org.ayf.reports.Report;
import org.ayf.ui.BackgroundPanel;

/**
 *
 * @author om
 */
public class GenericSearchDialog extends javax.swing.JDialog
{
    /**
     * Creates new form GenericSearchDialog
     */
    
    protected ReportDataProcessor dataProcessor;
    protected Report report;
    
    public GenericSearchDialog(final Report report, final ReportDataProcessor dataProcessor, final java.awt.Frame parent, boolean modal) throws InvalidArgument 
    {
        super(parent, modal);
        initComponents();
        
        if(report == null)
        {
            throw new InvalidArgument("null report object");
        }

        setDataProcessor(dataProcessor);
        setReport(report);
        
        add(getReport().getView(), BorderLayout.CENTER);
        
        setSize(700, 450);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        
        addWindowListener(new java.awt.event.WindowAdapter() 
        {
            @Override
            public void windowOpened(WindowEvent e) {
                getReport().updateReport();
            }
        });
    }
    
    @Override
    protected JRootPane createRootPane() 
    {
        ActionListener actionListener = new ActionListener() 
        {
            public void actionPerformed(ActionEvent actionEvent) 
            {
               setVisible(false);
            }
        };
        
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        JRootPane rootPane = new JRootPane();
        rootPane.registerKeyboardAction(actionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);
        return rootPane;
    }

    public void setDataProcessor(ReportDataProcessor dataProcessor) {
        this.dataProcessor = dataProcessor;
    }

    public ReportDataProcessor getDataProcessor() {
        return dataProcessor;
    }

    public Report getReport() {
        return report;
    }

    public void setReport(Report report) {
        this.report = report;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new BackgroundPanel(BackgroundPanel.BackgroundStyle.GradientBlueGray);
        selectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .add(cancelButton)
                .add(18, 18, 18)
                .add(selectButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(selectButton)
                    .add(cancelButton))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        if(getDataProcessor() != null)
        {
            getDataProcessor().processSelectedData(getReport().getView().getSelectedReportData(), getReport().getView());
        }
        
        setVisible(false);
    }//GEN-LAST:event_selectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables

}
