/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ayf.reports.views;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.text.DecimalFormat;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.ayf.reports.Report;
import org.ayf.reports.ReportData;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.title.TextTitle;

/**
 *
 * @author om
 */
public class GenericCustomReportView extends BaseReportView {

    static BufferedImage img = null;
    
    ChartPanel pieChartPanel = null;
    /**
     * Creates new form DonationReportView
     */
    public GenericCustomReportView(Report report) {
        super(report);
        initComponents();
        setupTextSearchForReportTable(new JTextField());
        this.remove(this.jScrollPane1);
        
        pieChartPanel = new ChartPanel(null);
        pieChartPanel.setBackground(new Color(0));
     
        pieChartPanel.setLayout(new BorderLayout());
        
    }

    public JTable getReportTable() {
        return reportTable;
    }

     
    @Override
    public void updateViewDecoration(ReportData data)
    {   
        this.rootPanel.add(pieChartPanel, BorderLayout.EAST);
        
        if(data == null) return;
        
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), getDisplayName(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        
        String description = getDisplayName();
        
        switch(getReport().getReportType())
        {
            case DashboardDonation:
                description = "Total Donation By Type";
                break;
            case DashboardExpenses:
                description = "Total Expense By Type";
                break;
        }
        
        this.reportDetailLabel.setText(description);
        
        
        JFreeChart objChart = ChartFactory.createPieChart (
        description,   //Chart title
        data.getPieChartDataSet(),          //Chart Data 
        true,               // include legend?
        true,               // include tooltips?
        false               // include URLs?
        );

        objChart.getPlot().setBackgroundAlpha(0);
        
        Font font = JFreeChart.DEFAULT_TITLE_FONT.deriveFont(JFreeChart.DEFAULT_TITLE_FONT.getSize() - 4);
        TextTitle title = new TextTitle(description, font);
        
        objChart.setTitle(title);
        
        pieChartPanel.setChart(objChart);
        PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
            "{0}: {1} ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));
        PiePlot plot = (PiePlot)objChart.getPlot();
        plot.setLabelGenerator(gen);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        reportDetailLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        rootPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new ReportTable();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Donation Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        reportDetailLabel.setText("Total Donation Amount by Type");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        rootPanel.setLayout(new java.awt.GridLayout(1, 2));

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(reportTable);

        rootPanel.add(jScrollPane1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(reportDetailLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 50, Short.MAX_VALUE)
                        .add(refreshButton))
                    .add(rootPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(refreshButton)
                    .add(reportDetailLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(rootPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        if(report != null)
        {
            report.updateReport();
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel reportDetailLabel;
    private javax.swing.JTable reportTable;
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables

}
