/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ayf.reports.views;

import javax.swing.JTable;
import org.ayf.models.GenericDefaultTableModel;
import org.ayf.reports.Report;
import org.ayf.reports.ReportData;

/**
 *
 * @author om
 */
public class GenericSearchReportView extends BaseReportView {

    /**
     * Creates new form GenericSearchReport
     */
    public GenericSearchReportView(Report report) {
        super(report);
        initComponents();
        
        setupTextSearchForReportTable(this.searchTxtField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentSearchPanel = new javax.swing.JPanel();
        searchTextPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        footerPanel = new javax.swing.JPanel();
        caseSensitiveButton = new javax.swing.JCheckBox();

        jLabel1.setText("Type text to search record");

        jLabel2.setText("Matching Records");

        org.jdesktop.layout.GroupLayout searchTextPanelLayout = new org.jdesktop.layout.GroupLayout(searchTextPanel);
        searchTextPanel.setLayout(searchTextPanelLayout);
        searchTextPanelLayout.setHorizontalGroup(
            searchTextPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(searchTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(searchTextPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .add(searchTxtField)
                    .add(searchTextPanelLayout.createSequentialGroup()
                        .add(jLabel2)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchTextPanelLayout.setVerticalGroup(
            searchTextPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(searchTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(searchTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel2)
                .add(6, 6, 6))
        );

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(reportTable);

        org.jdesktop.layout.GroupLayout tablePanelLayout = new org.jdesktop.layout.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .add(6, 6, 6))
        );

        caseSensitiveButton.setText("Case Sensitive");
        caseSensitiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseSensitiveButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout footerPanelLayout = new org.jdesktop.layout.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(footerPanelLayout.createSequentialGroup()
                .add(caseSensitiveButton)
                .add(0, 0, Short.MAX_VALUE))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(caseSensitiveButton)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout parentSearchPanelLayout = new org.jdesktop.layout.GroupLayout(parentSearchPanel);
        parentSearchPanel.setLayout(parentSearchPanelLayout);
        parentSearchPanelLayout.setHorizontalGroup(
            parentSearchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(parentSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(parentSearchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, tablePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, searchTextPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(footerPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        parentSearchPanelLayout.setVerticalGroup(
            parentSearchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(parentSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(searchTextPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tablePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(footerPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(parentSearchPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(parentSearchPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void caseSensitiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseSensitiveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseSensitiveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox caseSensitiveButton;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel parentSearchPanel;
    private javax.swing.JTable reportTable;
    private javax.swing.JPanel searchTextPanel;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView(ReportData data) {
        if(data != null)
        {
            getReportTable().setModel(new GenericDefaultTableModel(data));
            adjustReportTableColumns();
        }
    }

    @Override
    protected JTable getReportTable() {
        return this.reportTable;
    }
}
