/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ayf.reports.views;


import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import javax.swing.RepaintManager;
import javax.swing.UIManager;
import org.ayf.reports.print.PrintableView;

/**
 *
 * @author om
 */
public class HTMLPrintable extends PrintableView {

    /**
     * Creates new form HTMLPrintable
     */
    String html;

    public HTMLPrintable(String html, Paper paper, Insets margins) 
    {
        initComponents();
        initUI();
        
        setHtml(html);
        
        if(paper == null)
            paper = new Paper();
        
        if(margins == null)
            margins = new Insets(10, 10, 10, 10);
        
        this.editorView.setSize((int)paper.getImageableWidth(), (int)paper.getImageableHeight());
    }

    public String getHtml() {
        return html;
    }

    public void setHtml(String html) {
        this.html = html;
        this.editorView.setContentType("text/html");
        this.editorView.setText(html);
    }

    @Override
    /**
     * The method @print@ must be implemented for @Printable@ interface.
     * Parameters are supplied by system.
     */
    public int print(Graphics g, PageFormat pf, int pageIndex)
            throws PrinterException {
        Graphics2D g2 = (Graphics2D) g;

        RepaintManager.currentManager(this.editorView).setDoubleBufferingEnabled(false);
        Dimension d = this.editorView.getSize();    //get size of document
        double panelWidth = d.width;    //width in pixels
        double panelHeight = d.height;   //height in pixels
        double pageHeight = pf.getImageableHeight();   //height of printer page
        double pageWidth = pf.getImageableWidth();    //width of printer page
        double scale = pageWidth / panelWidth;
        int totalNumPages = (int) Math.ceil(scale * panelHeight / pageHeight);

        // Make sure not print empty pages
        if (pageIndex >= totalNumPages) {
            return Printable.NO_SUCH_PAGE;
        }

        // Shift Graphic to line up with beginning of print-imageable region
        g2.translate(pf.getImageableX(), pf.getImageableY());
        // Shift Graphic to line up with beginning of next page to print
        g2.translate(0f, -pageIndex * pageHeight);
        // Scale the page so the width fits...
        g2.scale(0.8, 0.8);
        
        this.editorView.print(g2);
        return PAGE_EXISTS;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editorView = new javax.swing.JEditorPane();

        jScrollPane1.setViewportView(editorView);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editorView;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initUI() {
        Font font = UIManager.getFont("Label.font");
//        String bodyRule = "body { font-family: " + font.getFamily() + "; " +
//                "font-size: " + font.getSize() + "pt; }";
//        ((HTMLDocument)editorView.getDocument()).getStyleSheet().addRule(bodyRule);
//        
        editorView.setOpaque(false);
        editorView.setBorder(null);
        editorView.setEditable(false);
    }
}
