/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ayf.reports.views;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.Date;
import java.text.DecimalFormat;
import javax.swing.JTable;
import org.ayf.managers.DatabaseManager;
import org.ayf.reports.Report;
import org.ayf.reports.ReportData;
import org.ayf.reports.ReportSpecificData;
import org.ayf.util.DateTime;
import org.ayf.util.StartEndYear;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.title.TextTitle;

/**
 *
 * @author om
 */
public class MemberRegisterationReportView extends BaseReportView {

    DatabaseManager.GroupingOption groupingOption = DatabaseManager.GroupingOption.Year;
    ChartPanel pieChartPanel = null;
    ChartPanel barChartPanel = null;
    
    
    /**
     * Creates new form MemberRegisterationReport
     */
    public MemberRegisterationReportView(Report report) {
        super(report);
        initComponents();
        initUI();
    }
    
    public StartEndYear getStartEndYear() {
        return (StartEndYear)this.yearComboBox.getSelectedItem();
    }
    
    public Date getStartYear() {
        return getStartEndYear().getStartYear();
    }

    public Date getEndYear() {
        return getStartEndYear().getEndYear();
    }

    public DatabaseManager.GroupingOption getGroupingOption() {
        return groupingOption;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        yearRadioBtn = new javax.swing.JRadioButton();
        monthRadioBtn = new javax.swing.JRadioButton();
        yearComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        statementDescriptionLabel = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalMembersLabel = new javax.swing.JLabel();
        totalActiveMembersLabel = new javax.swing.JLabel();
        totalDeactiveMembersLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Total Registeration By");

        yearRadioBtn.setText("Year");
        yearRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearRadioBtnActionPerformed(evt);
            }
        });

        monthRadioBtn.setText("Month");
        monthRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthRadioBtnActionPerformed(evt);
            }
        });

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Year");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        statementDescriptionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        statementDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statementDescriptionLabel.setText("jLabel3");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(statementDescriptionLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(34, 34, 34)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(yearRadioBtn)
                                .add(18, 18, 18)
                                .add(monthRadioBtn))
                            .add(yearComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(refreshButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(statementDescriptionLabel)
                .add(25, 25, 25)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(yearRadioBtn)
                    .add(monthRadioBtn)
                    .add(refreshButton))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(yearComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(18, 18, 18))
        );

        reportPanel.setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(reportTable);

        reportPanel.add(jScrollPane1);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Total Members       :");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Active Members     : ");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Deactive Members : ");

        totalMembersLabel.setText("jLabel6");

        totalActiveMembersLabel.setText("jLabel7");

        totalDeactiveMembersLabel.setText("jLabel8");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Summary");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel5)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(32, 32, 32)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(totalMembersLabel)
                            .add(totalActiveMembersLabel)
                            .add(totalDeactiveMembersLabel))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel6)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(totalMembersLabel))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(totalActiveMembersLabel))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(totalDeactiveMembersLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reportPanel.add(jPanel3);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(reportPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(reportPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yearRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearRadioBtnActionPerformed
        this.monthRadioBtn.setSelected(false);

        this.groupingOption = DatabaseManager.GroupingOption.Year;

        updateReportInternal();
    }//GEN-LAST:event_yearRadioBtnActionPerformed

    private void monthRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthRadioBtnActionPerformed
        this.yearRadioBtn.setSelected(false);

        this.groupingOption = DatabaseManager.GroupingOption.Month;

        updateReportInternal();
    }//GEN-LAST:event_monthRadioBtnActionPerformed

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        updateReportInternal();
    }//GEN-LAST:event_yearComboBoxActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        updateReportInternal();
    }//GEN-LAST:event_refreshButtonActionPerformed


    private void initUI() {
        
        this.yearRadioBtn.setSelected(true);
        this.monthRadioBtn.setSelected(false);
        
        populateYearCombo();
        
        this.yearComboBox.setSelectedIndex(0);
        
        pieChartPanel = new ChartPanel(null);
        pieChartPanel.setBackground(new Color(0));
        pieChartPanel.setLayout(new BorderLayout());
        
        barChartPanel = new ChartPanel(null);
        barChartPanel.setBackground(new Color(0));
        barChartPanel.setLayout(new BorderLayout());
        
        this.reportPanel.add(this.pieChartPanel);
        this.reportPanel.add(this.barChartPanel);
        
        updateStatementDescriptionLabel();
        updateReportSummary();
        
    }
    
    

    private void populateYearCombo() {
        java.sql.Date year = DateTime.getFiscalYearStart(DateTime.getFoundationEstablishmentDate());
        java.sql.Date today = DateTime.getTodaySQL();
        
        int todayYear = DateTime.getYear(today);
        
        this.yearComboBox.removeAllItems();
        
        this.yearComboBox.addItem(new StartEndYear(year, DateTime.getFiscalYearEnd(today)));
        
        while(DateTime.getYear(year) <= todayYear)
        {
            this.yearComboBox.insertItemAt(new StartEndYear(year, DateTime.getFiscalYearEnd(year)), 1);
            year = DateTime.dateByAdding(year, 0, 0, 1);
        }
    }

    private void updateReportInternal() {
        
        updateStatementDescriptionLabel();
        updateReportSummary();
        refresh();
        
    }

    @Override
    public void updateViewDecoration(ReportData data) 
    {
        {
            JFreeChart objChart = ChartFactory.createPieChart (
            null,   //Chart title
            data.getPieChartDataSet(),          //Chart Data 
            true,               // include legend?
            true,               // include tooltips?
            false               // include URLs?
            );

            objChart.getPlot().setBackgroundAlpha(0);

            pieChartPanel.setChart(objChart);
            PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
                "{0}: {1} ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));
            PiePlot plot = (PiePlot)objChart.getPlot();
            plot.setLabelGenerator(gen);
        }
        
        {
            JFreeChart objChart = ChartFactory.createBarChart(
                null,   //Chart title
                groupingOption.toString(),
                "Members Registered",
                data.getCategoryDataSet(),          //Chart Data 
                PlotOrientation.VERTICAL, // orientation
                true,                     // include legend
                true,                     // tooltips?
                false                     // URLs?
            );

            objChart.getPlot().setBackgroundAlpha(0);
//
//            Font font = JFreeChart.DEFAULT_TITLE_FONT.deriveFont(JFreeChart.DEFAULT_TITLE_FONT.getSize() - 4);
//            TextTitle title = new TextTitle("Donation Statemnt", font);
//
//            objChart.setTitle(title);

            
            barChartPanel.setChart(objChart);
//            PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
//                "{0}: {1} ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));
//            PiePlot plot = (PiePlot)objChart.getPlot();
//            plot.setLabelGenerator(gen);
        }
        
        updateReportSummary();
    }

    @Override
    protected JTable getReportTable() {
        return this.reportTable;
    }

    private void updateStatementDescriptionLabel() 
    {
        String description = "";
        switch(this.groupingOption)
        {
            case Month:
            {
                description = "Total new members registered by month in year "+this.yearComboBox.getSelectedItem();
                break;
            }
            case Year:
            {
                description = "Total new members registred in year "+this.yearComboBox.getSelectedItem();
                break;
            }
        }
        
        this.statementDescriptionLabel.setText(description);
    }

    private void updateReportSummary() {
        ReportData data = this.getReport().getData();
        ReportSpecificData reportSpecificData = data != null ? data.getReportSpecificData() : null;
        if(data == null || reportSpecificData == null)
        {
            this.totalActiveMembersLabel.setText("");
            this.totalDeactiveMembersLabel.setText("");
            this.totalMembersLabel.setText("");
            return;
        }
        
        this.totalActiveMembersLabel.setText(Integer.toString(reportSpecificData.getTotalActiveMembers()));
        this.totalDeactiveMembersLabel.setText(Integer.toString(reportSpecificData.getTotalDeactiveMembers()));
        this.totalMembersLabel.setText(Integer.toString(reportSpecificData.getTotalMemberCount()));
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton monthRadioBtn;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JTable reportTable;
    private javax.swing.JLabel statementDescriptionLabel;
    private javax.swing.JLabel totalActiveMembersLabel;
    private javax.swing.JLabel totalDeactiveMembersLabel;
    private javax.swing.JLabel totalMembersLabel;
    private javax.swing.JComboBox yearComboBox;
    private javax.swing.JRadioButton yearRadioBtn;
    // End of variables declaration//GEN-END:variables
}
