/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ayf.ui;

import javax.swing.JComponent;

/**
 *
 * @author om
 */
public class ReportView extends javax.swing.JPanel {

    /**
     * Creates new form ReportView
     */
    public ReportView() {
        initComponents();
    }
    
    public void addView(JComponent view)
    {
        if(view != null)
        {
            rootPanel.add(view);
        }
    }

    
    public void cleanView() 
    {
        rootPanel.removeAll();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rootPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        rootPanel.setLayout(new java.awt.GridLayout(2, 2));
        jScrollPane1.setViewportView(rootPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables

    
}
