/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ayf.ui;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.Vector;
import javax.swing.JComponent;
import org.ayf.reports.views.BaseReportView;

/**
 *
 * @author om
 */
public class ReportView extends javax.swing.JPanel {

    /**
     * Creates new form ReportView
     */
    
    public ReportView() {
        initComponents();
    }
    
    public void addView(JComponent view)
    {
        if(view != null)
        {
            rootPanel.add(view);
            rootPanel.repaint(view.getBounds());
        }
    }

    
    public void cleanView() 
    {
        rootPanel.removeAll();
        rootPanel.repaint();
    }
    
    public void prepareForReports(int count)
    {
        if(count == 1)
        {
            this.rootPanel.setLayout(new BorderLayout());
        }
        else
        {
            this.rootPanel.setLayout(new GridLayout(2, 2));
        }
    }
    
    public Vector<BaseReportView> getReportViews()
    {
        Vector<BaseReportView> reportViews = new Vector<BaseReportView>();
        
        for(int i=0; i<rootPanel.getComponentCount(); ++i)
        {
            if(rootPanel.getComponent(i).getClass().equals(BaseReportView.class))
            {
                reportViews.add(((BaseReportView)rootPanel.getComponent(i)));
            }
        }
        
        return reportViews;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rootPanel = new BackgroundPanel();

        setLayout(new java.awt.BorderLayout());

        rootPanel.setLayout(new java.awt.GridLayout(2, 2));
        jScrollPane1.setViewportView(rootPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    //private BackgroundPanel rootPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables

    public void printReport() 
    {
        if(rootPanel.getComponentCount() == 0)
            return;
        
        BaseReportView reportView = (BaseReportView)rootPanel.getComponent(0);
        
    }

    
}
