/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ayf.reports.print;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.io.FileUtils;
import org.ayf.managers.ResourceManager;

/**
 *
 * @author om
 */
public class ReceiptPrintableView extends PrintableView {

    /**
     * Creates new form ReceiptPrintableView
     */
    public ReceiptPrintableView() {
        initComponents();
    }

    @Override
    public String getHtml()
    {
        File file = ResourceManager.getResource("/org/ayf/resources/html/", "HTMLLayoutReceipt.html");
        if(file.exists())
        {
            try {
                String html = FileUtils.readFileToString(file);
                return prepareHtml(html);
            } catch (IOException ex) {
                Logger.getLogger(HTMLPrintable.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        return null;
    }

    @Override
    protected String prepareHtml(String html) {
        
        html = html.replace("__date__", "01/08/2014");
        html = html.replace("__regid__", "AUF/01/2013");
        html = html.replace("__name__", "Omkar Nagorao Ramtekkar");
        html = html.replace("__name1__", "---------");
        html = html.replace("__amount_in_words__", "One thousand two hundred");
        html = html.replace("__check_drawn_on__", "---------");
        html = html.replace("__check_drawn_date__", "01/3/4567");
        html = html.replace("__type__", "Cash");
        html = html.replace("__y1__", "13");
        html = html.replace("__y2__", "14");
        html = html.replace("__amount__", "1200/-");
        
        return html;
    }

    @Override
    String getDisplayName() {
        return "Receipt";
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 307, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
